version: '3.3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    container_name: todos-azuread-app
  database:
    build:
      dockerfile: Dockerfile
      context: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
    container_name: todos-azuread-db
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
